trigger: none

name: 'orttraining_ci_$(Date:yyyyMMdd)_$(Rev:r)'
pool: 'AMD-GPU'

variables:
- group: pai-variables
- name: pai-user
  value: onnxrt

steps:
- checkout: self
  clean: true

- script: |-
    python3 -m pip install -r tools/ci_build/github/pai/requirements.txt
  displayName: 'Install requirements'

- script: |-
    python3 tools/ci_build/github/pai/run_job.py
  displayName: 'Run PAI job'
  env:
    # map secret variables to environment variables
    PAI_USER: $(pai-user)
    PAI_TOKEN: $(pai-token)
    DOCKER_USER: $(pai-docker-user)
    DOCKER_TOKEN: $(pai-docker-token)
